### PR TITLE
DC-2590: Correct Fossa project ID

### PR DESCRIPTION
**Pull request by helobinvn**

### CODE REVIEW

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=214):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/5/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/5/ : SUCCESS in 59s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/343/ : SUCCESS in 6s

**Comment by r0039** [comment]
LGTM

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=214):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=214&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/180/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/6/ : SUCCESS in 32s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-premerge/2/ : SUCCESS in 1m 01s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul/4/ : FAILURE in 2m 08s (non-voting)

**Pull request merged**
