### PR TITLE
RELATED: RAIL-2786 - Fix authentication glitches

### PR DESCRIPTION
**Pull request by lupko**
-  'Login' is shown even if the user is already logged in (has valid cookies etc). This was problem with bear because of bad default auth provider.

-  Clean up backend setup code

### CODE REVIEW

**Comment by yenkins** [comment]
## The code coverage **improved** with your change! 🎉
You are the best! Like literary the best!
#### Report (compared to build [#167](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/167/))
Covered lines: **26.8%**, change: **0%**
Covered branches: **25.93%**, change: **3.35%** (additional 8 branches are covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/168/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/168/ : SUCCESS in 1m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/139/ : SUCCESS in 5s

**Comment by yenkins** [comment]
## The code coverage **improved** with your change! 🎉
You are the best! Like literary the best!
#### Report (compared to build [#167](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/167/))
Covered lines: **26.8%**, change: **0%**
Covered branches: **25.93%**, change: **3.35%** (additional 8 branches are covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/169/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/169/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/140/ : SUCCESS in 6s

**Comment by yenkins** [comment]
## The code coverage **improved** with your change! 🎉
You are the best! Like literary the best!
#### Report (compared to build [#167](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/167/))
Covered lines: **26.8%**, change: **0%**
Covered branches: **25.93%**, change: **3.35%** (additional 8 branches are covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/170/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/170/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/141/ : SUCCESS in 8s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
## The code coverage **improved** with your change! 🎉
You are the best! Like literary the best!
#### Report (compared to build [#167](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/167/))
Covered lines: **26.8%**, change: **0%**
Covered branches: **25.93%**, change: **3.35%** (additional 8 branches are covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/171/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/61/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/171/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul-el7/26/ : SUCCESS in 13s (non-voting)

**Pull request merged**
