### PR TITLE
RELATED: RAIL-2808 make sure the refresh-ldm script works on Windows

### PR DESCRIPTION
**Pull request by no23reason**
There seems to be an issue on Windows with the .bin folder, for example jest hit it
https://github.com/facebook/jest/issues/4751#issuecomment-361063215

JIRA: RAIL-2808

### CODE REVIEW

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#163](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/163/))
Covered lines: **26.8%**, change: **0%**
Covered branches: **22.58%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/164/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/164/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/137/ : SUCCESS in 7s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/59/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/165/ : SUCCESS in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul-el7/24/ : SUCCESS in 15s (non-voting)

**Pull request merged**
