### PR TITLE
TRIVIAL: Remove duplicate code

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=212):
    
    [Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG) [1 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG)
    [Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY)
    [Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/1/ : FAILURE in 28s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/1/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/339/ : SUCCESS in 6s

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=212):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG) [1 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/2/ : SUCCESS in 27s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/2/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/340/ : SUCCESS in 6s

**Comment by tomaso** [comment]
OK, let's remove the buggy code (commit) now.

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=212):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/3/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/3/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/341/ : SUCCESS in 6s

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=212):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=212&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/179/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/4/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-premerge/1/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul/3/ : FAILURE in 1m 18s (non-voting)

**Pull request merged**
