### PR TITLE
DC-2590: Correct Fossa project ID

### PR DESCRIPTION
**Pull request by helobinvn**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/7/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/7/ : FAILURE in 3s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/345/ : SUCCESS in 9s

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=216):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/8/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/8/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/346/ : SUCCESS in 5s

**Comment by yenkins** [comment]
[SonarCloud scan results](https://sonarcloud.io/dashboard?id=gooddata-create-gooddata-react-app&pullRequest=216):
    
[Bug](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=BUG)
[Vulnerability](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=VULNERABILITY)
[Code Smell](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=gooddata-create-gooddata-react-app&pullRequest=216&resolved=false&types=CODE_SMELL)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/181/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/9/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-premerge/3/ : SUCCESS in 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul/5/ : FAILURE in 1m 17s (non-voting)

**Pull request merged**
