### PR TITLE
RELATED: FET-1201 update pkg

### PR DESCRIPTION
**Pull request by ivanmjartan**
JIRA: FET-1201

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/10/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/9/ : FAILURE in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/347/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/11/ : SUCCESS in 31s
- https://checklist.intgdc.com/job/compliance/job/sonarcloud-scan-PR-check/10/ : FAILURE in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/348/ : SUCCESS in 5s

**Comment by tomaso** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/12/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/349/ : SUCCESS in 5s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/182/ : SUCCESS in 30s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker/13/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul/6/ : FAILURE in 1m 14s (non-voting)

**Pull request merged**
