### PR TITLE
RELATED: RAIL-3920 upgrade dependencies

### PR DESCRIPTION
**Pull request by no23reason**
Upgrade several dependencies of both the CLI tool and the bootstrapped app.
Bring the bootstrapped app to React 17.

The only peerDependency react-related warnings are for
* react-codemirror2
* react-truncate
* react-router-use-location-state
* use-location-state

All of these work fine with React 17, they just have not updated their peerDependencies.

See individual commits for details.

### CODE REVIEW

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#301](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/301/))
Covered lines: **22.73%**, change: **0.76%** (additional 1 lines are covered)
Covered branches: **33.33%**, change: **-0.92%** (additional 2 branches are not covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/302/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/302/ : SUCCESS in 1m 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/247/ : SUCCESS in 10s

**Review by plavemar — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/120/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/303/ : SUCCESS in 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul-el7/85/ : FAILURE in 3m 22s (non-voting)

**Pull request merged**
