### PR TITLE
RELATED: RAIL-2711 use SDK 8.0.0

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Review by kandl — APPROVED** [review]
LGTM

**Comment by tomasreichmann** [comment]
🎉👏

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#157](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/157/))
Covered lines: **26.8%**, change: **0%**
Covered branches: **22.58%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/158/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/57/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/158/ : SUCCESS in 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul-el7/22/ : FAILURE in 4m 14s (non-voting)

**Pull request merged**
