### PR TITLE
RELATED: RAIL-3191 remove docker stuff in tiger builds

### PR DESCRIPTION
**Pull request by no23reason**
We do not have a good enough docker configuration for tiger at the moment, so we remove the mentions of it altogether in tiger.

### CODE REVIEW

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#210](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/210/))
Covered lines: **23.39%**, change: **-1.83%** (additional 9 lines are not covered)
Covered branches: **38.46%**, change: **-1.22%** (additional 2 branches are not covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/211/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/211/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-oss-check/174/ : SUCCESS in 6s

**Review by lupko — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#210](https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/210/))
Covered lines: **23.39%**, change: **-1.83%** (additional 9 lines are not covered)
Covered branches: **38.46%**, change: **-1.22%** (additional 2 branches are not covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/212/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-merge-compliance-check/76/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-create-gooddata-react-app-unit-tests-zuul-docker-el7/212/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-create-gooddata-react-app-fossa-scanning-zuul-el7/41/ : FAILURE in 4m 02s (non-voting)

**Pull request merged**
